"""fix Users table

Revision ID: 15d646ab8d4f
Revises: 53418ec839e4
Create Date: 2023-02-27 15:16:42.828325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d646ab8d4f'
down_revision = '53418ec839e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
