"""add constraint

Revision ID: 53418ec839e4
Revises: c46fad4e9957
Create Date: 2023-02-27 00:30:34.859093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53418ec839e4'
down_revision = 'c46fad4e9957'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    # ### end Alembic commands ###
